# Generated by Django 4.1.2 on 2022-10-11 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Google'), (2, 'Facebook'), (3, 'Linkedin')], default=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('website', models.URLField(max_length=256, null=True)),
                ('images', models.ImageField(null=True, upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'account',
            },
        ),
    ]
